name: Linux

on: [ push, pull_request, workflow_dispatch ]

env:
  CCACHE_VERSION: 4.2.1
  CCACHE_DIR: ${{ github.workspace }}/ccache
  CCACHE_COMPRESS: true
  CCACHE_COMPRESSLEVEL: 6
  CCACHE_NLEVELS: 4

jobs:
  build:
    runs-on:
      ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: get-date
        run: |
          echo "::set-output name=date::$(/bin/date -u "+%Y%m%d-%H%M%S")"
      
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ env.CCACHE_DIR }}/
            game/tf2vintage/bin/
            src/lib/public/linux32/mathlib.a
            src/lib/public/linux32/tier1.a
            src/lib/public/linux32/raytrace.a
            src/lib/public/linux32/vgui_controls.a
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}
          restore-keys: ${{ runner.os }}-
      
      - name: Configure dependencies
        run: sudo apt update && sudo apt install -y build-essential gcc-multilib g++-multilib
      
      - name: Download ccache
        id: ccache
        shell: cmake -P {0}
        run: |
          set(ccache_url "https://github.com/cristianadam/ccache/releases/download/v$ENV{CCACHE_VERSION}/${{ runner.os }}.tar.xz")
          file(DOWNLOAD "${ccache_url}" ./ccache.tar.xz SHOW_PROGRESS)
          execute_process(COMMAND ${CMAKE_COMMAND} -E tar xvf ./ccache.tar.xz)
          file(COPY ./ccache DESTINATION src/devtools/bin/linux USE_SOURCE_PERMISSIONS)
      
      - name: Setup ccache
        run: |
          cd src
          sudo mkdir ./ccache/tmp
          cd devtools/bin/linux
          sudo ./ccache --set-config cache_dir=$CCACHE_DIR
          sudo ./ccache --set-config compression_level=6

      - name: Create project
        run: cd src && sudo devtools/bin/vpc /tf2vintage +game /mksln TF2vintage
      
      - name: Download Steam runtime
        run: |
          cd /
          sudo mkdir valve
          cd valve
          sudo wget http://media.steampowered.com/client/runtime/steam-runtime-sdk_latest.tar.xz
          sudo tar xvf steam-runtime-sdk_latest.tar.xz
          sudo mv steam-runtime-sdk_2013-09-05 steam-runtime

      - name: Build project
        run: |
          sudo bash $STEAM_RUNTIME_PATH/setup.sh --release --target="i386 amd64" --auto-upgrade
          cd src && sudo make -f TF2vintage.mak
        env:
          STEAM_RUNTIME_PATH: /valve/steam-runtime
      
      - name: Pack
        run: sudo tar cJfv Linux.tar.xz game/tf2vintage/bin

      - name: Upload product
        uses: actions/upload-artifact@v2
        with:
          name: TF2Vintage
          path: Linux.tar.xz
